cloudposse/terraform-aws-rds

main.tf
variables.tf

* Assign `attributes` and `tags` from `variables.tf` to internal `label` module
* The internal `label` module's `attributes` and `tags` should be visible from outside of the top-level module
* If `attributes` and `tags` are not accessible from outside, sometimes it's impossible to create more than one AWS resource from the top-level module
* Without additional `attributes`, it's not possible at all to create `aws_security_group` inside the module since many security groups with the same name `${module.label.id}` are created in the same solution

Assign `attributes` and `tags` from `variables.tf` to internal `label` module

---

README.md
main.tf
variables.tf

* Add `db_parameter` option
* Sometimes we need to add special parameters to the RDS database

Add `db_parameter` option

---

README.md
main.tf
variables.tf

* Add `snapshot_identifier`
* We need this option for restoring RDS instance from the snapshot

Add snapshot_identifier

---

main.tf

* Fix incorrect origin for DNS host name
* Remove `timstamp()` from `final_snapshot_identifier` label
* DNS name doesn't work
* `timastamp()` causes infinite pending changes

Fix incorrect origin for DNS host name

---

.travis.yml
LICENSE
Makefile
README.md
examples/complete/main.tf
main.tf
outputs.tf

* Use `splat + join` syntax for outputs from resources with counts
* Added TravisCI
* To address the issue https://github.com/cloudposse/terraform-aws-rds/issues/10
* To fix terraform warnings
> Warning: output "parameter_group_id": must use splat syntax to access aws_db_parameter_group.default attribute "id", because it has "count" set; use aws_db_parameter_group.default.*.id to obtain a list of the attributes across all instances

Use `splat + join` syntax for outputs from resources with counts

---

README.md
README.yaml
docs/targets.md
docs/terraform.md
examples/complete/main.tf
main.tf
variables.tf

* Make `database_user` and `database_password` optional
* Make `dns_zone_id` optional
* https://github.com/cloudposse/terraform-aws-rds/issues/15
* If `snapshot_identifier` is provided to restore the database from the snapshot, `database_user` and `database_password` are not required and TF should not ask for it
* Not all applications require creating Route53 sub-domains for the DB host

Make `database_user` and `database_password` optional. Make `dns_zone_id` optional

---

main.tf

* Must use splat operator when using `count` and value may be zero
* `Resource 'aws_db_instance.default' not found for variable 'aws_db_instance.default.address'`

Fix enabled/disable behavior

---

README.md
README.yaml
docs/terraform.md
main.tf
outputs.tf
variables.tf

RE: https://www.terraform.io/docs/providers/aws/r/db_instance.html
- Added support for the license_model parameter, required for some engines like SQL Server.   Defaults to empty string, and AWS will fill this in with open source database engines, but it's required for commercial ones.  
- Added support for the db_option_group - and is modeled after the parameter_group feature in this model.   The module will always create it, but the user can point to an existing one.
- Tested both features where the end user defines these features, or doesn't.

Added support for license_model and option_group creation needed for some db engines

---

README.md
docs/terraform.md
main.tf
variables.tf

This setting allows for existing SGs to be assigned to the RDS instance,
which allows for setups where other services have Security Groups which
have rules pointing to existing target groups, and we add this RDS instance
to that target group.
The result is the RDS is a member of multiple Security Groups, one built by this
module to control ingress rules specific to this instance, and others which are defined
elsewhere that might add common rules to multiple RDS instances, or allow this instance
to be accessed by existing egress rules on other resources which point to a common security group.

Added `server_security_group_ids`

---

README.md
docs/terraform.md
main.tf
variables.tf

RDS now supports a deletion_protection flag, similar to the
termination_protection flag on EC2 instaces. If enabled, this
flag will prevent the accidental deletion of a database. This
require the terraform AWS provider be at least version 1.39.0.

Added deletion_protection parameter for RDS instances

---

main.tf

`major_engine_version` is not a required parameter, while `engine_version` is, but not providing it leads to errors when creating the `db_option_group`.
This PR changes it, so that it uses the `engine_version` parameter and extracts the major version from it (the first two segments), if no `major_engine_version` parameter was provided.

Calculate major engine version if not provided

---

main.tf

* fix of computing major version in case of postgres engine
* there is a different pattern for postrges versioning, so this fix respects it

fix for computed_major_engine_version in case of postgres

---

README.md
README.yaml
docs/terraform.md
main.tf
variables.tf

Adds `allowed_cidr_blocks` to support whitelisting IP ranges for connecting to RDS instances outside of AWS. 
This is directly similar to cloudposse/terraform-aws-rds-cluster's `allowed_cidr_blocks` https://github.com/cloudposse/terraform-aws-rds-cluster/blob/master/variables.tf#L172

Adds `allowed_cidr_blocks` support to RDS SG 

---

examples/complete/fixtures.us-east-2.tfvars
main.tf
test/src/examples_complete_test.go

* Add standalone ingress/egress rules to the RDS security group
* Change AWS region for tests
* Inlined security group rules force re-creation when a separate rule is added to the security group in a top-level module using `aws_security_group_rule` (`aws_security_group_rule` and inline rules don't mix)
* `us-west-1` is a limited region, e.g. it has different names of AZs for different AWS accounts

Add standalone ingress/egress rules to the RDS security group. Change AWS region for tests

---

README.md
docs/terraform.md
main.tf
variables.tf

* Add standalone ingress/egress rules to the RDS security group
* Add `allowed_cidr_blocks`
* Inlined security group rules force re-creation when a separate rule is added to the security group in a top-level module using `aws_security_group_rule` (`aws_security_group_rule` and inline rules don't mix)
* This is for TF 0.11
* For TF 0.12, see https://github.com/cloudposse/terraform-aws-rds/releases/tag/0.14.0

Add standalone ingress/egress rules to the RDS security group. Add `allowed_cidr_blocks`

---

README.md
docs/terraform.md
main.tf
variables.tf

Motivation: Allow to configure [Performance Insights](https://aws.amazon.com/rds/performance-insights/) for RDS

feat: Add RDS Performance Insights arguments

---

main.tf

1. The code as it exists fails for postgres engine versions below 10 because the computed_major_engine_version returns 9 instead of 9.x.   
2. It also fails for upgrades to an existing database because of issues with creating an option group with the same name, and with deleting a parameter group that is already in use.  
The changes in this pull request address the two issues listed above.

Bugfix support old postgres versions and allow upgrade

---

main.tf

* upgrade cloudposse/terraform-aws-route-53-cluster-hostname to 0.5.0
* for TF 0.13.0 support
* https://github.com/cloudposse/terraform-aws-route53-cluster-hostname/releases/tag/0.5.0

Additional TF 0.13.0 changes

---

README.md
docs/terraform.md
main.tf
variables.tf

* adds a `monitoring_role_arn` input variable which gets passed through to `aws_db_instance` resource
* without this, when using `monitoring_interval`, you get the following error:
> InvalidParameterCombination: A MonitoringRoleARN value is required if you specify a MonitoringInterval value other than 0.
* this is already [supported by `cloudposse/terraform-aws-rds-cluster`](https://github.com/cloudposse/terraform-aws-rds-cluster/blob/0.35.0/variables.tf#L233-L236)

Support monitoring_role_arn; required for monitoring_interval

---

README.md
docs/terraform.md
versions.tf

* Update aws provider to `>= 2.0` avoid module version conflicts when used with `>= 3.0` modules (eg. aws-eks-node-group).
* This module is being used with [terraform-aws-eks-node-group](https://github.com/cloudposse/terraform-aws-eks-node-group) which needs aws provider version to be `>= 2.0` to fix version conflicts.
* See cloudposse/terraform-aws-eks-node-group#41 for details. This tackles one of the modules causing the issue.

fix: update aws provider version

---

main.tf

* Bump module dns_host_name from 0.5.0 to 0.7.0
* terraform-aws-rds claims to support provider AWS >= 2.0
* terraform-aws-route53-cluster-hostname supports AWS ~> 2.0
* By bumping terraform-aws-route53-cluster-hostname to a version supporting AWS >= 2.0 we ensure that this RDS module's dependencies don't imply unexpected restrictions.
* terraform-aws-route53-cluster-hostname 0.6.0 would also be valid; but 0.7.0 causes no breaking changes, so it makes sense to skip ahead to the latest valid version.

Bump terraform-aws-route53-cluster-hostname

---

main.tf

* Use `dns_name` instead of `name` while using the route53-cluster-hostname module.
* The `name` parameter is not being used by the route53-cluster-hostname module invocation and results it falling back to the value of `module.this.id` rather than the default value of `db` for `host_name` within the terraform-aws-rds module.
* https://github.com/cloudposse/terraform-aws-route53-cluster-hostname/blob/master/main.tf#L3

fix: use correct variable with route53-cluster-hostname

---

.github/workflows/auto-context.yml

- Fix `auto-context` workflow so that it creates a pull request when `context.tf` changes
- Bugfix
After verifying that this works to produce a PR that is automatically merged, same fix needs to be applied to `build-harness`

[auto-context] Create pull request when context.tf changes

---

.github/workflows/auto-context.yml
.github/workflows/validate-codeowners.yml
README.md

- Upgrade to support Terraform 0.14 and bring up to current Cloud Posse standard
- Support Terraform 0.14

Terraform 0.14 upgrade

---

.github/auto-release.yml
.github/mergify.yml
.github/workflows/auto-context.yml
.github/workflows/auto-format.yml
.github/workflows/auto-release.yml
.github/workflows/validate-codeowners.yml
README.md
context.tf
docs/terraform.md
examples/complete/context.tf
main.tf
versions.tf

- update context.tf to v0.23.0 
- minimum required Terraform version bumped to 0.13.0 
- readme updated, Bridgecrew compliance badges added
- It allows for setting the letter case of tag names and labels
- we have dropped support for Terraform 0.12
- To be able see and fix the recommendations from Bridgecrew so we can position our modules as standards compliant
Supersedes and closes #96 
Supersedes and closes #97 
Supersedes and closes #98

minimum required Terraform version bumped to 0.13.0, context.tf updated, readme updated

---

README.md
docs/terraform.md
variables.tf

* With terraform `0.13` If `snapshot_identifier` is set to "" then the resource creation will fail (`"snapshot_identifier": conflicts with username`). 
* Apparently it works with `>0.14` instead.
It seems `resource "aws_db_instance" "default"` defined into main changed (apparently, an hour ago?) its flexibility in taking arguments. Before (also with `0.13`) defining `""` was enough to use username and password for the DB. Now, I've got this:
```
Error: ConflictsWith                                                                                                                                                                       
on .terraform/modules/rds_instance/main.tf line 44, in resource "aws_db_instance" "default": …
```

Terraform 0.13 requires snapshot_identifier explicitly set to null

---

.github/mergify.yml
.github/workflows/auto-format.yml
.github/workflows/auto-release.yml
LICENSE
README.md
docs/terraform.md
examples/complete/main.tf
examples/complete/outputs.tf
examples/complete/variables.tf
main.tf
outputs.tf
test/src/examples_complete_test.go
variables.tf

* Add `create_before_destroy` for parameter group
* Make the names for parameter & option groups unique
* Make subnet group optional
* Bump module versions
* Update example and terratest
* You cannot delete a parameter/option group while it is in use, but you can update a database with a new parameter/option group, so in order to change parameter/option groups, you need to create a new one, install it, then delete the old one
* Some update and destroy operations were failing because resources were being deleted in the wrong order
* If `var.db_subnet_group_name` is provided, use it and don't create a new Subnet Group
* If `var.availability_zone` is provided (and `var.db_subnet_group_name` and `var.subnet_ids` are not), use `var.availability_zone` to place the instance into the default VPC …

Add `create_before_destroy` for parameter group. Make subnet group optional

---

.github/workflows/validate-codeowners.yml
README.md
docs/terraform.md
outputs.tf

* Exports the resource_id
* The `resource_id` is needed in order to create a least-privileges IAM policy to provide using RDS IAM authentication. 
* Use `closes #111`

Add an output to export resource_id

---

README.md
docs/terraform.md
versions.tf

Removed an unused terraform provider: hashicorp/template
This provider was not used anywhere in the module. It is also deprecated and there is no `darwin_arm64` version available, so I was unable to use this module with an M1 mac

Remove unused provider: hashicorp/template

---

.github/CODEOWNERS
.github/auto-release.yml
.github/workflows/auto-context.yml
.github/workflows/auto-format.yml
.github/workflows/auto-readme.yml
.github/workflows/auto-release.yml
.github/workflows/chatops.yml
.github/workflows/validate-codeowners.yml
Makefile
README.md

Change all references to `git.io/build-harness` into `cloudposse.tools/build-harness`, since `git.io` redirects will stop working on April 29th, 2022.
- DEV-143

git.io->cloudposse.tools update

---

.github/renovate.json
README.md
docs/terraform.md
examples/complete/fixtures.us-east-2.tfvars
examples/complete/main.tf
examples/complete/versions.tf
main.tf
variables.tf
versions.tf

* Adding the ability to specify timezone for MSSQL RDS instances
* This variable is available to the terraform resource type so it should be available to the component
* Legacy databases and applications may not handle date conversion and offset properly and by default RDS sets timezone to UTC
* https://aws.amazon.com/premiumsupport/knowledge-center/rds-change-time-zone/

Add `timezone` variable for mssql

---

.github/auto-release.yml
main.tf

* update to allow null value for replicas
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#db_subnet_group_name
* Subnets need to be null for replicas

Allow null subnets for Replicas

---

.github/renovate.json
.github/workflows/release-branch.yml
.github/workflows/release-published.yml
README.md
docs/terraform.md
examples/complete/main.tf
examples/complete/versions.tf
examples/mssql/main.tf
examples/mssql/versions.tf
main.tf
outputs.tf
versions.tf

- Support AWS Provider V5
- Notable: ID output breaking (in regards to provider version compatibility) change https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-5-upgrade#resourceaws_db_instance
- Linter fixes
Maintenance
https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.0.0

Support AWS Provider V5
